config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :budgets
  resources :gastos
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    namespace :active_storage do
      resources :variant_records
    end
    namespace :active_storage do
      resources :attachments
    end
    namespace :active_storage do
      resources :blobs
    end
    resources :users
    resources :services
    resources :notifications
    resources :announcements
    root to: "dashboard#show"
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/budget.rb
class Budget < ApplicationRecord
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: %i[ show edit update destroy ]

  # GET /budgets or /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1 or /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets or /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: "Budget was successfully created." }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1 or /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: "Budget was successfully updated." }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1 or /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: "Budget was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budget_params
      params.require(:budget).permit(:nombre, :descripcion, :valor)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= simple_form_for(@budget) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :descripcion %>
    <%= f.input :valor %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Edit Budget</h1>

<%= render 'form', budget: @budget %>

app/views/budgets/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Cotizaciones</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_budget_path, class: 'btn btn-primary' do %>
    Agregar cotización
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Valor</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @budgets.each do |budget| %>
        <%= content_tag :tr, id: dom_id(budget), class: dom_class(budget) do %>
          

                      <td><%= budget.nombre %></td>
                      <td><%= budget.descripcion %></td>
                      <td><%= number_to_currency(budget.valor, delimiter: ".", precision: 0) %></td>
          
          
            <td><%= link_to 'Ver', budget %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/budgets/new.html.erb
<h1>New budget</h1>

<%= render 'form', budget: @budget %>

app/views/budgets/show.html.erb
<div class="page-header">
  <%= link_to budgets_path, class: 'btn btn-default' do %>
    All Budgets
  <% end %>
  <%= link_to edit_budget_path(@budget), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show budget</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nombre:</dt>
  <dd><%= @budget.nombre %></dd>

  <dt>Descripcion:</dt>
  <dd><%= @budget.descripcion %></dd>

  <dt>Valor:</dt>
  <dd><%= @budget.valor %></dd>

</dl>