config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :budgets
  resources :gastos
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    namespace :active_storage do
      resources :variant_records
    end
    namespace :active_storage do
      resources :attachments
    end
    namespace :active_storage do
      resources :blobs
    end
    resources :users
    resources :services
    resources :notifications
    resources :announcements
    root to: "dashboard#show"
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/gasto.rb
class Gasto < ApplicationRecord
end

app/controllers/gastos_controller.rb
class GastosController < ApplicationController
  before_action :set_gasto, only: %i[ show edit update destroy ]

  # GET /gastos or /gastos.json
  def index
    @gastos = Gasto.all
  end

  # GET /gastos/1 or /gastos/1.json
  def show
  end

  # GET /gastos/new
  def new
    @gasto = Gasto.new
  end

  # GET /gastos/1/edit
  def edit
  end

  # POST /gastos or /gastos.json
  def create
    @gasto = Gasto.new(gasto_params)

    respond_to do |format|
      if @gasto.save
        format.html { redirect_to action: "index", notice: "Gasto creado." }
        format.json { render :show, status: :created, location: @gasto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gastos/1 or /gastos/1.json
  def update
    respond_to do |format|
      if @gasto.update(gasto_params)
        format.html { redirect_to @gasto, notice: "Gasto actualizado." }
        format.json { render :show, status: :ok, location: @gasto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gastos/1 or /gastos/1.json
  def destroy
    @gasto.destroy
    respond_to do |format|
      format.html { redirect_to gastos_url, notice: "Gasto eliminado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gasto
      @gasto = Gasto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gasto_params
      params.require(:gasto).permit(:fecha, :descripcion, :monto, :comentarios, :estado)
    end
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/views/gastos/_form.html.erb
<%= form_with(model: gasto, local: true) do |form| %>
  <% if gasto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gasto.errors.count, "error") %> prohibited this gasto from being saved:</h2>

      <ul>
      <% gasto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :fecha %>
    <%= form.date_select :fecha, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :monto %>
    <%= form.number_field :monto, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :comentarios %>
    <%= form.text_field :comentarios, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :estado %>
    <%= form.select :estado, ["Pagado", "Pendiente"] %>
  </div>

 



  <div class="form-group">
    <% if gasto.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', gasto, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if gasto.persisted? %>
      <%= link_to "Cancel", gasto, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", gastos_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/gastos/edit.html.erb
<h1>Edit Gasto</h1>

<%= render 'form', gasto: @gasto %>

app/views/gastos/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Gastos</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_gasto_path, class: 'btn btn-primary' do %>
    Agregar Gasto
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Fecha</th>
            <th>Descripcion</th>
            <th>Monto</th>
            <th>Comentarios</th>
            <th>Estado</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @gastos.each do |gasto| %>
        <%= content_tag :tr, id: dom_id(gasto), class: dom_class(gasto) do %>
          

                      <td><%= gasto.fecha %></td>
                      <td><%= gasto.descripcion %></td>
                      <td><%= number_to_currency(gasto.monto, delimiter: ".", precision: 0) %></td>
                      <td><%= gasto.comentarios %></td>
                      <td><%= gasto.estado %></td>
          
          
            <td><%= link_to 'Ver', gasto %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/gastos/new.html.erb
<h1>Nuevo gasto</h1>

<%= render 'form', gasto: @gasto %>

app/views/gastos/show.html.erb
<div class="page-header">
  <%= link_to gastos_path, class: 'btn btn-default' do %>
    All Gastos
  <% end %>
  <%= link_to edit_gasto_path(@gasto), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show gasto</h1>
</div>

<dl class="dl-horizontal">
  <dt>Fecha:</dt>
  <dd><%= @gasto.fecha %></dd>

  <dt>Descripcion:</dt>
  <dd><%= @gasto.descripcion %></dd>

  <dt>Monto:</dt>
  <dd><%= @gasto.monto %></dd>

  <dt>Comentarios:</dt>
  <dd><%= @gasto.comentarios %></dd>

  <dt>Estado:</dt>
  <dd><%= @gasto.estado %></dd>

</dl>